import React, { useState } from 'react';
import { CheckCircle2, GitBranch, Lightbulb } from 'lucide-react';
import { classNames } from '../lib/utils.js';
import { PageIntro } from '../components/PageIntro.jsx';

export const connectorLessons = [
  { id: 'add', title: 'Ajouter une idée', label: 'B1', time: '8 min', words: ['de plus', 'également', 'par ailleurs', 'aussi', 'en outre', 'qui plus est'], purpose: 'pour apporter une information qui renforce ton idée', rule: 'Utilise-les après une première information complète. « Aussi » est plus naturel au milieu d’une phrase ; les autres se placent facilement en début de phrase.', caution: 'Évite d’accumuler plusieurs connecteurs d’ajout dans une seule phrase.', examples: [{ word: 'De plus,', text: ' le délai est réaliste et l’équipe connaît déjà l’outil.' }, { word: 'Par ailleurs,', text: ' le client a validé la maquette hier.' }, { word: 'En outre,', text: ' cette solution réduit les coûts de maintenance.' }], practice: { sentence: 'Le plan est clair. ___, tous les responsables ont confirmé leur disponibilité.', answer: 'De plus', options: ['Cependant', 'De plus', 'Donc'], feedback: '« De plus » ajoute une information qui renforce la première phrase.' } },
  { id: 'cause', title: 'Expliquer une cause', label: 'B1', time: '9 min', words: ['car', 'en effet', 'puisque', 'parce que', 'grâce à', 'en raison de', 'du fait de'], purpose: 'pour donner la raison d’un fait ou d’une décision', rule: '« Car », « puisque » et « parce que » introduisent une proposition. « Grâce à », « en raison de » et « du fait de » sont suivis d’un nom ou d’un groupe nominal.', caution: '« Grâce à » introduit une cause positive ; pour une difficulté, préfère « en raison de ».', examples: [{ word: 'Car', text: ' les tests ne sont pas terminés, nous reportons la livraison.' }, { word: 'Grâce à', text: ' la préparation de l’équipe, la démonstration s’est bien passée.' }, { word: 'En raison de', text: ' l’incident, le service reste indisponible ce matin.' }], practice: { sentence: '___ la documentation complète, les nouveaux collègues ont été autonomes rapidement.', answer: 'Grâce à', options: ['Grâce à', 'Cependant', 'Par conséquent'], feedback: '« Grâce à » convient à une cause positive suivie d’un groupe nominal.' } },
  { id: 'contrast', title: 'Opposer deux idées', label: 'B2', time: '10 min', words: ['mais', 'cependant', 'pourtant', 'toutefois', 'néanmoins', 'en revanche', 'alors que', 'tandis que'], purpose: 'pour marquer une différence, une limite ou une contradiction', rule: '« Cependant », « toutefois » et « néanmoins » relient souvent deux phrases. « Alors que » et « tandis que » introduisent directement la seconde proposition.', caution: '« En revanche » exprime une compensation ou un autre aspect, pas forcément une opposition forte.', examples: [{ word: 'Cependant,', text: ' la solution demande une surveillance régulière.' }, { word: 'Alors que', text: ' la première option est rapide, la seconde est plus durable.' }, { word: 'En revanche,', text: ' le coût d’hébergement sera plus faible.' }], practice: { sentence: 'La maquette est séduisante. ___, elle ne respecte pas encore les contraintes d’accessibilité.', answer: 'Cependant', options: ['Cependant', 'En somme', 'Grâce à'], feedback: '« Cependant » introduit ici une limite qui contraste avec la première idée.' } },
  { id: 'result', title: 'Montrer une conséquence', label: 'B2', time: '10 min', words: ['donc', 'ainsi', 'alors', 'par conséquent', 'c’est pourquoi', 'de ce fait', 'si bien que'], purpose: 'pour présenter le résultat logique de ce qui précède', rule: 'Place « donc » au cœur d’une phrase. Utilise « par conséquent », « ainsi » ou « de ce fait » au début d’une nouvelle phrase pour rendre le raisonnement plus formel.', caution: 'Ne confonds pas « donc » (conséquence) avec « parce que » (cause).', examples: [{ word: 'Donc,', text: ' nous pouvons commencer la mise en ligne demain.' }, { word: 'Par conséquent,', text: ' le lancement est reporté à lundi.' }, { word: 'Si bien que', text: ' le client a reçu la réponse avant midi.' }], practice: { sentence: 'Le calendrier est déjà partagé ; ___ chacun peut préparer la réunion.', answer: 'ainsi', options: ['cependant', 'ainsi', 'certes'], feedback: '« Ainsi » introduit la conséquence du calendrier déjà partagé.' } },
  { id: 'nuance', title: 'Nuancer son avis', label: 'B2 avancé', time: '12 min', words: ['certes', 'toutefois', 'néanmoins', 'en partie', 'dans une certaine mesure', 'même si', 'bien que'], purpose: 'pour reconnaître un point avant d’apporter une réserve ou une limite', rule: 'La structure « certes… toutefois… » est très utile à l’écrit. « Bien que » est suivi du subjonctif : « bien que la solution soit simple ».', caution: 'Une nuance ne consiste pas à affaiblir ton idée : elle montre que tu as considéré les limites.', examples: [{ word: 'Certes,', text: ' cette option réduit le coût initial ; toutefois, elle augmente la dette technique.' }, { word: 'Même si', text: ' le délai est court, nous devons tester les parcours essentiels.' }, { word: 'Dans une certaine mesure,', text: ' cette proposition répond au besoin du client.' }], practice: { sentence: '___ cette option est rapide, elle risque de créer une dette technique.', answer: 'Même si', options: ['Même si', 'Par conséquent', 'En outre'], feedback: '« Même si » permet de reconnaître un avantage avant d’exprimer une réserve.' } },
  { id: 'conclusion', title: 'Conclure', label: 'C1', time: '10 min', words: ['en somme', 'bref', 'en définitive', 'enfin', 'pour conclure', 'en conclusion', 'au final'], purpose: 'pour rassembler les idées et formuler une position finale', rule: 'Une conclusion reprend l’idée essentielle puis indique clairement la décision, la recommandation ou la suite à donner.', caution: 'Ne commence pas chaque dernier paragraphe par « en conclusion » : varie avec « en somme » ou « en définitive ».', examples: [{ word: 'En somme,', text: ' une migration progressive limite le risque tout en maintenant le service.' }, { word: 'En définitive,', text: ' le gain de performance justifie l’investissement initial.' }, { word: 'Pour conclure,', text: ' je recommande de valider le scénario B.' }], practice: { sentence: '___, je recommande de tester la solution sur un périmètre réduit avant le déploiement général.', answer: 'En définitive', options: ['En définitive', 'Pourtant', 'En raison de'], feedback: '« En définitive » introduit une position finale après un raisonnement.' } },
];

const connectorExtensions = {
  add: {
    words: ['de même', 'en complément', 'de surcroît', 'sans compter que'],
    examples: [{ word: 'Également,', text: ' le service juridique relira la version finale.' }, { word: 'Aussi,', text: ' l’équipe prévoit un temps de formation.' }, { word: 'Qui plus est,', text: ' la solution reste compatible avec les outils existants.' }, { word: 'De même,', text: ' les équipes régionales recevront le même support.' }, { word: 'En complément,', text: ' un guide pratique sera envoyé aux utilisateurs.' }, { word: 'De surcroît,', text: ' le coût de déploiement est inférieur aux prévisions.' }, { word: 'Sans compter que', text: ' cette approche facilite les futures évolutions.' }],
  },
  cause: {
    words: ['à cause de', 'faute de', 'compte tenu de'],
    examples: [{ word: 'En effet,', text: ' les données confirment l’intérêt de cette amélioration.' }, { word: 'Puisque', text: ' le client est disponible, organisons la démonstration demain.' }, { word: 'Parce que', text: ' le besoin a changé, nous revoyons le périmètre.' }, { word: 'Du fait de', text: ' la mise à jour, certains accès doivent être renouvelés.' }, { word: 'À cause de', text: ' la panne réseau, la réunion a commencé plus tard.' }, { word: 'Faute de', text: ' validation, la publication reste en attente.' }, { word: 'Compte tenu de', text: ' ces contraintes, nous retenons une version allégée.' }],
  },
  contrast: {
    words: ['au contraire', 'à l’inverse'],
    examples: [{ word: 'Mais', text: ' le budget prévu ne couvre pas encore la maintenance.' }, { word: 'Pourtant,', text: ' les utilisateurs avaient signalé ce besoin dès janvier.' }, { word: 'Toutefois,', text: ' nous pouvons limiter le risque avec un test pilote.' }, { word: 'Néanmoins,', text: ' la décision doit être prise cette semaine.' }, { word: 'Tandis que', text: ' le site public évolue vite, l’espace client reste stable.' }, { word: 'Au contraire,', text: ' cette modification simplifie le parcours.' }, { word: 'À l’inverse,', text: ' la seconde option exige davantage de formation.' }],
  },
  result: {
    words: ['dès lors', 'par suite', 'en conséquence'],
    examples: [{ word: 'Ainsi,', text: ' chaque participant peut préparer ses questions à l’avance.' }, { word: 'Alors,', text: ' nous pourrons finaliser le contrat vendredi.' }, { word: 'C’est pourquoi', text: ' nous avons prévu une phase de vérification.' }, { word: 'De ce fait,', text: ' le temps de réponse a diminué.' }, { word: 'Dès lors,', text: ' il devient inutile de conserver l’ancien formulaire.' }, { word: 'Par suite,', text: ' les équipes pourront passer à l’étape suivante.' }, { word: 'En conséquence,', text: ' la direction valide le budget complémentaire.' }],
  },
  nuance: {
    words: ['malgré', 'quoi que', 'à condition que'],
    examples: [{ word: 'Toutefois,', text: ' nous devons protéger les données sensibles.' }, { word: 'Néanmoins,', text: ' le déploiement peut débuter sur un petit périmètre.' }, { word: 'En partie,', text: ' cette solution répond aux attentes exprimées.' }, { word: 'Bien que', text: ' la solution soit simple, elle demande des tests.' }, { word: 'Malgré', text: ' son coût, l’option reste pertinente à long terme.' }, { word: 'Quoi que', text: ' nous décidions, il faudra informer les utilisateurs.' }, { word: 'À condition que', text: ' les tests soient validés, nous lancerons la version.' }],
  },
  conclusion: {
    words: ['tout compte fait', 'dans l’ensemble', 'en résumé'],
    examples: [{ word: 'Bref,', text: ' nous disposons déjà des éléments nécessaires.' }, { word: 'Enfin,', text: ' il reste à confirmer la date de lancement.' }, { word: 'En conclusion,', text: ' ce scénario répond au besoin avec un risque maîtrisé.' }, { word: 'Au final,', text: ' le choix dépendra surtout du délai disponible.' }, { word: 'Tout compte fait,', text: ' la solution intermédiaire offre le meilleur compromis.' }, { word: 'Dans l’ensemble,', text: ' les retours des utilisateurs sont très favorables.' }, { word: 'En résumé,', text: ' lançons le test puis mesurons son impact.' }],
  },
};

const trainingExtensions = {
  add: [{ sentence: 'La solution est compatible avec les mobiles. ___, elle peut être déployée sans formation longue.', answer: 'En outre', options: ['En outre', 'Pourtant', 'En conclusion'], feedback: '« En outre » ajoute un second avantage à la solution.' }, { sentence: 'Le guide explique la procédure. ___, une vidéo accompagne chaque étape.', answer: 'Par ailleurs', options: ['Par ailleurs', 'À cause de', 'Donc'], feedback: '« Par ailleurs » introduit une information supplémentaire.' }],
  cause: [{ sentence: '___ les délais très courts, l’équipe a choisi de simplifier la première version.', answer: 'En raison de', options: ['En raison de', 'Ainsi', 'Toutefois'], feedback: '« En raison de » introduit ici la cause suivie d’un groupe nominal.' }, { sentence: '___ le client a confirmé son besoin, nous pouvons planifier le développement.', answer: 'Puisque', options: ['Puisque', 'En revanche', 'En somme'], feedback: '« Puisque » introduit une cause déjà connue ou évidente.' }],
  contrast: [{ sentence: 'Le test est concluant. ___, il doit encore être reproduit sur un autre navigateur.', answer: 'Toutefois', options: ['Toutefois', 'Grâce à', 'Par conséquent'], feedback: '« Toutefois » annonce une réserve après un point positif.' }, { sentence: '___ le support reçoit moins de demandes, les retours clients sont plus précis.', answer: 'Tandis que', options: ['Tandis que', 'En conclusion', 'À cause de'], feedback: '« Tandis que » permet de mettre deux constats en parallèle.' }],
  result: [{ sentence: 'Le client a validé le périmètre. ___, nous pouvons lancer la phase de réalisation.', answer: 'Dès lors', options: ['Dès lors', 'Bien que', 'En revanche'], feedback: '« Dès lors » présente la suite logique d’une décision.' }, { sentence: 'La base de données a été optimisée, ___ les recherches sont beaucoup plus rapides.', answer: 'si bien que', options: ['si bien que', 'puisque', 'toutefois'], feedback: '« Si bien que » relie une cause à son résultat.' }],
  nuance: [{ sentence: '___ le budget soit limité, le projet reste réalisable en deux étapes.', answer: 'Bien que', options: ['Bien que', 'En outre', 'Donc'], feedback: 'Après « bien que », on utilise le subjonctif : « soit ».' }, { sentence: 'Cette idée est intéressante, ___ elle ne répond pas à tous les besoins.', answer: 'dans une certaine mesure', options: ['dans une certaine mesure', 'par conséquent', 'grâce à'], feedback: 'Cette expression permet d’apporter une réserve mesurée.' }],
  conclusion: [{ sentence: '___, les retours sont positifs et le risque est maîtrisé : validons le test pilote.', answer: 'En résumé', options: ['En résumé', 'Cependant', 'Parce que'], feedback: '« En résumé » rassemble les éléments avant la décision.' }, { sentence: '___, l’option B est la plus adaptée à nos contraintes actuelles.', answer: 'Tout compte fait', options: ['Tout compte fait', 'Tandis que', 'Du fait de'], feedback: '« Tout compte fait » annonce une conclusion après comparaison.' }],
};

export function ConnectorsView({ lessons = connectorLessons }) {
  const [activeId, setActiveId] = useState('add');
  const [answers, setAnswers] = useState({});
  const active = lessons.find((lesson) => lesson.id === activeId) || lessons[0];
  const extension = connectorExtensions[active.id];
  const expressions = [...active.words, ...extension.words];
  const examples = [...active.examples, ...extension.examples];
  const practiceExamples = [active.practice, ...trainingExtensions[active.id]];

  return <div className="page connectors-page">
    <PageIntro className="connectors-intro" eyebrow="COURS PRATIQUE · B1 À C1" title="Connecteurs logiques" description="Choisis le lien entre tes idées, puis utilise le connecteur qui rend ta phrase claire et naturelle." mark={<><GitBranch size={34} /><span>une idée,<br />un lien</span></>} />
    <div className="connectors-layout">
      <aside className="connector-lesson-list" aria-label="Leçons sur les connecteurs">{connectorLessons.map((lesson) => <button key={lesson.id} className={classNames('connector-lesson-choice', lesson.id === active.id && 'active')} onClick={() => { setActiveId(lesson.id); setAnswers({}); }}><span>{lesson.label}</span><b>{lesson.title}</b></button>)}</aside>
      <section className="connector-course" aria-live="polite"><div className="connector-course-head"><div><span className="pill lavender-pill">{active.label}</span><h2>{active.title}</h2></div><span className="connector-time">Temps estimé : {active.time}</span><p>{active.purpose}</p></div><div className="connector-expression-head"><p className="little-label">EXPRESSIONS À RETENIR</p><span>{expressions.length} expressions</span></div><div className="connector-words">{expressions.map((word) => <span key={word}>{word}</span>)}</div><article className="connector-examples"><div className="connector-examples-head"><p className="little-label">EXEMPLES EN CONTEXTE</p><span>{examples.length} exemples</span></div>{examples.map((example) => <p key={example.word}><b>{example.word}</b>{example.text}</p>)}</article><div className="connector-notes"><article><p className="little-label">MODE D’EMPLOI</p><p>{active.rule}</p></article><article className="caution"><Lightbulb size={17} aria-hidden="true" /><div><p className="little-label">POINT D’ATTENTION</p><p>{active.caution}</p></div></article></div></section>
    </div>
    <section className="connector-practice"><div><p className="eyebrow">MINI-ENTRAÎNEMENT · {active.label}</p><h2>Choisis le bon connecteur dans chaque contexte</h2><p>Trois situations différentes pour réutiliser les expressions de la leçon.</p></div><div className="connector-practice-list">{practiceExamples.map((practice, index) => { const choice = answers[index]; const checked = Boolean(choice); return <article className="connector-practice-item" key={practice.sentence}><span>CONTEXTE {String(index + 1).padStart(2, '0')}</span><p>{practice.sentence}</p><div className="connector-options">{practice.options.map((option) => <button key={option} type="button" disabled={checked} className={classNames('connector-option', checked && option === practice.answer && 'correct', checked && choice === option && option !== practice.answer && 'wrong')} onClick={() => setAnswers((current) => ({ ...current, [index]: option }))}>{option}</button>)}</div>{checked && <p className={classNames('connector-feedback', choice === practice.answer && 'success')}>{choice === practice.answer ? <><CheckCircle2 size={16} /> Exact : {practice.feedback}</> : <>À retenir : {practice.feedback}</>}</p>}</article>; })}</div></section>
  </div>;
}
