export const stages = [
  {
    id: 'b1-solide', number: '01', level: 'B1', title: 'Parler avec aisance', color: 'peach', icon: '☀', duration: '2 à 3 mois',
    description: 'Relie tes idées, raconte avec précision et exprime ton avis sans préparer chaque phrase.',
    lessons: [
      { id: 'b1-temps', title: 'Raconter avec les bons temps', category: 'Conjugaison', time: '18 min', explanation: 'Alterne passé composé pour les actions terminées, imparfait pour le contexte, futur et conditionnel présent pour les projets et les hypothèses.', examples: ['J’ai résolu le problème alors que l’équipe travaillait déjà.', 'Demain, je présenterai la solution.', 'À ta place, je commencerais par le test.'], tip: 'Dans un récit, pose le décor à l’imparfait puis raconte l’événement au passé composé.', question: 'Quelle phrase décrit correctement le contexte ?', choices: ['Hier, il pleuvait quand je suis sorti.', 'Hier, il a plu quand je sortais.', 'Hier, il pleuvra quand je suis sorti.'], answer: 0 },
      { id: 'b1-connecteurs', title: 'Relier et nuancer ses idées', category: 'Expression', time: '15 min', explanation: 'Les connecteurs permettent de construire une pensée claire : opposition, conséquence, comparaison et concession.', examples: ['Le délai est court ; cependant, le périmètre est clair.', 'Nous avons simplifié l’interface, donc le parcours est plus fluide.', 'Tandis que l’API évolue, le client reste compatible.'], tip: 'Choisis un seul connecteur précis plutôt que de répéter « et » ou « mais ».', question: 'Quel connecteur exprime une opposition ?', choices: ['Par conséquent', 'Cependant', 'Donc'], answer: 1 },
      { id: 'b1-ecrire', title: 'Écrire une opinion structurée', category: 'Expression écrite', time: '16 min', explanation: 'Un texte de 120 à 180 mots présente une position, deux raisons illustrées, puis une conclusion nette.', examples: ['À mon avis, cette décision est pertinente.', 'D’abord, elle réduit le risque de régression.', 'En conclusion, je recommande de la valider.'], tip: 'Utilise la structure : avis → raison → exemple, deux fois, puis une conclusion.', question: 'Quelle phrase introduit une conclusion ?', choices: ['En effet,', 'Par exemple,', 'En conclusion,'], answer: 2 },
      { id: 'b1-resumer', title: 'Résumer sans répéter', category: 'Compréhension orale', time: '14 min', explanation: 'Après une vidéo ou un article, distingue l’idée principale des détails puis reformule avec ton propre vocabulaire.', examples: ['Le document explique surtout comment…', 'L’auteur insiste sur deux points : …', 'En résumé, il propose de…'], tip: 'Limite-toi à cinq à huit phrases : un résumé n’est pas une transcription.', question: 'Un bon résumé doit surtout…', choices: ['reprendre chaque détail', 'garder l’idée principale', 'donner uniquement son avis'], answer: 1 },
    ],
  },
  {
    id: 'b2-pro', number: '02', level: 'B2', title: 'Argumenter au travail', color: 'blue', icon: '◐', duration: '3 à 5 mois',
    description: 'Explique un problème, défends une décision et participe activement aux échanges professionnels.',
    lessons: [
      { id: 'b2-subjonctif', title: 'Exprimer la nécessité et le doute', category: 'Grammaire', time: '17 min', explanation: 'Le subjonctif présent apparaît après des expressions comme « il faut que », « bien que » et « afin que ».', examples: ['Il faut que nous priorisions les correctifs.', 'Bien que la solution soit simple, elle demande des tests.', 'Afin que le client comprenne, prépare une démo.'], tip: 'Après « il faut que », demande-toi : qui doit faire l’action ? Puis conjugue au subjonctif.', question: 'Quelle phrase est correcte ?', choices: ['Il faut que tu viens.', 'Il faut que tu viennes.', 'Il faut que tu viendras.'], answer: 1 },
      { id: 'b2-indirect', title: 'Rapporter une décision', category: 'Grammaire', time: '15 min', explanation: 'Le discours indirect permet de transmettre précisément ce qui a été décidé ou demandé dans une réunion.', examples: ['La responsable a indiqué que la livraison serait reportée.', 'Le client a demandé si nous pouvions ajouter cette option.', 'On m’a expliqué qu’il fallait revoir la priorité.'], tip: 'Avec un verbe au passé, vérifie le décalage des temps : « sera » devient « serait ».', question: 'Transforme : « Nous finirons demain », a-t-il dit.', choices: ['Il a dit que nous finirions demain.', 'Il a dit que nous finirons demain.', 'Il dit que nous finirions demain.'], answer: 0 },
      { id: 'b2-reunion', title: 'Proposer un compromis', category: 'Expression orale', time: '16 min', explanation: 'En réunion, reconnais un point de vue, exprime ta réserve, puis propose une solution concrète.', examples: ['Je reconnais que cette approche est rapide.', 'Toutefois, elle crée une dette technique.', 'Je propose donc de livrer une première version puis de consolider l’architecture.'], tip: 'La formule « je reconnais que…, toutefois… » aide à désamorcer un désaccord.', question: 'Quelle formule introduit une réserve polie ?', choices: ['C’est faux.', 'Toutefois, je crains que…', 'Tu dois changer.'], answer: 1 },
      { id: 'b2-presentation', title: 'Présenter une solution technique', category: 'Expression professionnelle', time: '20 min', explanation: 'Structure une présentation de cinq à sept minutes : contexte, problème, options, décision et impact.', examples: ['Le besoin initial était de réduire le temps de chargement.', 'Nous avons comparé deux approches.', 'La solution retenue améliore la performance sans bloquer l’équipe.'], tip: 'Annonce ton plan dès le début : les auditeurs suivront plus facilement ton raisonnement.', question: 'Quelle étape vient après la présentation du problème ?', choices: ['La conclusion sans explication', 'Les options envisagées', 'Une liste de mots isolés'], answer: 1 },
    ],
  },
  {
    id: 'b2-avance', number: '03', level: 'B2 avancé', title: 'Gagner en précision', color: 'lavender', icon: '✎', duration: '2 à 4 mois',
    description: 'Affines ta grammaire, ton registre et ta capacité à reformuler naturellement.',
    lessons: [
      { id: 'b2-relatifs', title: 'Préciser avec les pronoms relatifs', category: 'Grammaire', time: '17 min', explanation: 'Dont, lequel, auquel et leurs variantes évitent les répétitions et rendent les phrases plus précises.', examples: ['Voici le sujet dont nous avons parlé.', 'C’est la fonctionnalité à laquelle les utilisateurs tiennent.', 'Le service sur lequel nous comptons est maintenu.'], tip: 'Utilise « dont » lorsque le verbe se construit avec « de » : parler de, avoir besoin de, dépendre de.', question: 'Le projet ___ je suis responsable est prioritaire.', choices: ['dont', 'auquel', 'lequel'], answer: 0 },
      { id: 'b2-accords', title: 'Maîtriser les accords difficiles', category: 'Grammaire', time: '18 min', explanation: 'Le participe passé s’accorde selon l’auxiliaire et la place du complément. Relis les phrases qui contiennent « que », « les » ou « leur ».', examples: ['Les corrections que j’ai apportées sont en ligne.', 'Elle est arrivée avant la réunion.', 'Nous avons envoyé les documents.'], tip: 'Avec avoir, cherche le complément direct : s’il est placé avant le verbe, le participe s’accorde.', question: 'Les tâches que nous avons ___ sont terminées.', choices: ['terminé', 'terminées', 'terminer'], answer: 1 },
      { id: 'b2-reformuler', title: 'Reformuler une même idée', category: 'Style', time: '14 min', explanation: 'La reformulation évite les répétitions et permet d’adapter ton niveau de précision au public.', examples: ['Cette option est risquée.', 'Cette option comporte un risque.', 'Le niveau de risque de cette option est élevé.'], tip: 'Écris trois versions : directe, plus formelle, puis plus diplomatique.', question: 'Quelle formulation est la plus diplomatique ?', choices: ['Cette idée est mauvaise.', 'Cette option mérite d’être réévaluée.', 'Arrête cette idée.'], answer: 1 },
      { id: 'b2-feedback', title: 'Rédiger un message professionnel', category: 'Expression écrite', time: '16 min', explanation: 'Un message utile annonce le contexte, l’action attendue, l’échéance et une formule de collaboration adaptée.', examples: ['Je vous partage le compte rendu de notre échange.', 'Pourriez-vous confirmer ce point avant vendredi ?', 'Merci d’avance pour votre retour.'], tip: 'Préférez des demandes concrètes : une action, un responsable et une date.', question: 'Quelle demande est la plus précise ?', choices: ['Regarde ça.', 'Peux-tu valider la maquette avant jeudi midi ?', 'Il faut faire quelque chose.'], answer: 1 },
    ],
  },
  {
    id: 'c1', number: '04', level: 'C1', title: 'Convaincre et synthétiser', color: 'mint', icon: '◌', duration: '3 à 6 mois',
    description: 'Interviens avec souplesse dans des contextes exigeants, même face à un désaccord ou à un sujet complexe.',
    lessons: [
      { id: 'c1-argumenter', title: 'Construire une argumentation nuancée', category: 'Expression', time: '18 min', explanation: 'Une argumentation C1 anticipe les objections, reconnaît les limites et défend une conclusion équilibrée.', examples: ['Certes, cette migration demande un investissement initial.', 'Néanmoins, son coût à long terme serait inférieur.', 'Je recommande donc de la planifier par étapes.'], tip: 'Intègre un contre-argument réel : ton avis paraîtra plus crédible et plus réfléchi.', question: 'Quelle expression introduit une concession ?', choices: ['Certes,', 'Par conséquent,', 'En effet,'], answer: 0 },
      { id: 'c1-synthese', title: 'Synthétiser plusieurs sources', category: 'Expression écrite', time: '22 min', explanation: 'Une synthèse de 300 à 400 mots rapproche des sources, compare leurs positions et formule une conclusion personnelle.', examples: ['Les deux sources s’accordent sur le besoin de…', 'En revanche, elles divergent concernant…', 'Au regard de ces éléments, il semble préférable de…'], tip: 'Classe les idées par thème, pas article par article : la synthèse doit créer une vue d’ensemble.', question: 'Une synthèse efficace organise les idées…', choices: ['source par source uniquement', 'par thèmes et points de vue', 'dans l’ordre de lecture'], answer: 1 },
      { id: 'c1-desaccord', title: 'Gérer un désaccord en réunion', category: 'Expression orale', time: '18 min', explanation: 'Reformule la position de l’autre, expose ton désaccord avec calme, puis ouvre une voie de décision.', examples: ['Si je vous comprends bien, votre priorité est le délai.', 'Je partage cette contrainte, mais je vois un risque sur la qualité.', 'Pourrions-nous valider une version limitée cette semaine ?'], tip: 'Évite de répondre immédiatement : reformuler prouve l’écoute et clarifie le point de friction.', question: 'Quelle réaction aide à gérer un désaccord ?', choices: ['Couper la parole.', 'Reformuler le point de vue.', 'Éviter toute réponse.'], answer: 1 },
      { id: 'c1-improviser', title: 'Improviser une prise de parole', category: 'Expression orale', time: '20 min', explanation: 'Pour parler dix minutes, utilise un fil clair : constat, enjeux, options, recommandation et prochaine étape.', examples: ['Commençons par le constat.', 'Le principal enjeu concerne…', 'Pour avancer, je propose les trois étapes suivantes.'], tip: 'Garde trois expressions-pivots prêtes : « ce qui est en jeu », « en pratique », « la suite logique ».', question: 'Quel élément aide à improviser une intervention longue ?', choices: ['Un plan en cinq étapes', 'Une phrase unique répétée', 'Parler sans idée principale'], answer: 0 },
    ],
  },
];

export const allLessons = stages.flatMap((stage) => stage.lessons.map((lesson) => ({ ...lesson, stageId: stage.id, stageTitle: stage.title })));

export const writingPrompts = [
  { id: 'b1-opinion', title: 'Une décision au travail', level: 'B1', instruction: 'Une équipe doit-elle travailler à distance plusieurs jours par semaine ? Donne ton avis, deux raisons et un exemple.', target: 150, starters: ['À mon avis, …', 'D’abord, …', 'En conclusion, …'] },
  { id: 'b2-email', title: 'Un e-mail professionnel', level: 'B2', instruction: 'Rédige un e-mail pour signaler un risque sur un projet et proposer une solution à ton équipe.', target: 220, starters: ['Bonjour,', 'Je souhaite attirer votre attention sur…', 'Je propose que nous…'] },
  { id: 'b2-review', title: 'Commenter une pull request', level: 'B2 avancé', instruction: 'Explique de manière constructive pourquoi une modification d’API devrait être revue avant sa mise en production.', target: 250, starters: ['Merci pour cette proposition.', 'Il me semble toutefois que…', 'Une alternative serait de…'] },
  { id: 'c1-synthesis', title: 'Synthèse et recommandation', level: 'C1', instruction: 'Compare deux approches pour améliorer la performance d’une application, puis recommande celle qui te semble la plus durable.', target: 350, starters: ['Les deux approches visent à…', 'En revanche, …', 'Au regard de ces éléments, …'] },
];

export const speakingPrompts = [
  { id: 'b1-summary', title: 'Résume une actualité', level: 'B1', duration: 180, instruction: 'Résume une vidéo ou un article : donne le sujet, les deux idées essentielles et ton avis.', guide: ['Le document traite de…', 'Le point principal est…', 'Pour ma part, …'] },
  { id: 'b2-architecture', title: 'Présente une architecture React', level: 'B2', duration: 360, instruction: 'Présente le contexte, les composants importants, un choix technique et son impact sur les utilisateurs.', guide: ['Le besoin est…', 'Nous avons choisi…', 'Le bénéfice principal est…'] },
  { id: 'b2-incident', title: 'Explique un incident', level: 'B2 avancé', duration: 420, instruction: 'Explique un incident technique, ses causes possibles, les actions prises et ce que vous changerez ensuite.', guide: ['L’incident concernait…', 'Nous avons identifié…', 'Pour éviter que cela se reproduise…'] },
  { id: 'c1-decision', title: 'Défends une décision', level: 'C1', duration: 600, instruction: 'Défends une décision technique face à une objection : expose le contexte, le compromis et ta recommandation.', guide: ['La décision porte sur…', 'Je reconnais que…', 'Je recommande donc…'] },
];

export const weeklyPlan = [
  ['Lundi', 'Grammaire ciblée', 'Travaille un point précis pendant 20 minutes, puis écris cinq phrases personnelles.'],
  ['Mardi', 'Écoute active', 'Écoute 15 minutes sans sous-titres et note les idées essentielles.'],
  ['Mercredi', 'Expression écrite', 'Rédige un texte professionnel et relis-le avec la checklist.'],
  ['Jeudi', 'Lecture et vocabulaire', 'Lis un article ou une documentation, puis relève dix expressions utiles.'],
  ['Vendredi', 'Conversation', 'Explique une décision, un problème ou une actualité pendant au moins cinq minutes.'],
  ['Samedi', 'Présentation technique', 'Prépare une mini-présentation sur React, une API, l’accessibilité ou un design system.'],
  ['Dimanche', 'Bilan et reformulation', 'Corrige un texte, réécoute un enregistrement et reformule trois idées autrement.'],
];
