const makeLesson = (level, index, title, details = {}) => ({
  id: `grammar-${level.toLowerCase()}-${String(index).padStart(2, '0')}`,
  level,
  number: index,
  title,
  description: details.description || `Comprendre et employer ${title.toLowerCase()} dans des phrases utiles.`,
  duration: details.duration || '12 min',
  explanation: details.explanation || `Cette leçon te donne un repère clair pour utiliser ${title.toLowerCase()} avec plus d’aisance, à l’oral comme à l’écrit.`,
  rule: details.rule || `Repère la construction dans une phrase complète, puis réutilise-la dans un contexte qui t’est familier.`,
  examples: details.examples || [
    `Je vérifie cette règle avant d’envoyer mon e-mail.`,
    `L’équipe utilise cette construction pendant la réunion.`,
    `Nous pouvons l’appliquer dans notre prochain projet.`,
  ],
  caution: details.caution || 'Ne traduis pas mot à mot : observe la place des mots et la construction française.',
  tip: details.tip || 'Lis la phrase à voix haute, puis crée une phrase qui parle de ton quotidien ou de ton travail.',
  quiz: details.quiz || {
    question: `Quel réflexe aide à maîtriser « ${title} » ?`,
    options: ['Apprendre une phrase complète', 'Traduire chaque mot isolément', 'Éviter de pratiquer'],
    answer: 0,
    explanation: 'Une phrase complète montre la structure, le sens et le contexte d’emploi.',
  },
});

const a1Details = [
  { description: 'Identifier qui fait l’action.', rule: 'Les pronoms sujets remplacent le nom : je, tu, il/elle/on, nous, vous, ils/elles. Le verbe s’accorde avec eux.', examples: ['Je prépare la démo.', 'Nous travaillons sur le projet.', 'Elles arrivent à neuf heures.'], caution: '« On » se conjugue comme « il », même quand il signifie « nous ».', tip: 'Dans une présentation, commence par « Je vais… » ou « Nous allons… ».', quiz: { question: '___ préparons le compte rendu.', options: ['Nous', 'Vous', 'Ils'], answer: 0, explanation: 'Le verbe « préparons » correspond au pronom « nous ». ' } },
  { description: 'Utiliser quatre verbes indispensables au présent.', rule: 'Être : je suis ; avoir : j’ai ; aller : je vais ; faire : je fais. Apprends-les comme des blocs fréquents.', examples: ['Je suis disponible cet après-midi.', 'Nous avons une réunion.', 'Vous allez tester la version.', 'Elle fait une présentation.'], caution: 'On ne dit pas « je suis 30 ans » : pour l’âge, utilise « j’ai 30 ans ».', tip: 'Écris quatre phrases sur ta journée avec être, avoir, aller et faire.', quiz: { question: 'Nous ___ une réunion à 10 h.', options: ['avons', 'sommes', 'faites'], answer: 0, explanation: 'Avec une réunion, on utilise le verbe « avoir » : nous avons.' } },
  { description: 'Conjuguer les verbes réguliers au présent.', rule: 'Pour les verbes en -er, -ir et -re, enlève la terminaison de l’infinitif puis ajoute les terminaisons du présent.', examples: ['Je code une page.', 'Nous finissons le test.', 'Ils répondent au client.'], caution: 'Avec « nous », les verbes en -er finissent souvent par -ons : nous travaillons.', tip: 'Garde un modèle par groupe : parler, finir, attendre.', quiz: { question: 'Tu ___ au client.', options: ['réponds', 'répond', 'répondez'], answer: 0, explanation: 'Avec « tu », répondre se conjugue « tu réponds ». ' } },
  { description: 'Présenter un nom avec le bon article.', rule: 'Utilise le/la/les pour parler de quelque chose d’identifié ou en général ; un/une/des pour introduire une chose non identifiée.', examples: ['Le projet commence demain.', 'Une collègue arrive.', 'Les fichiers sont prêts.'], caution: 'Devant une voyelle, le et la deviennent l’ : l’application, l’équipe.', tip: 'Dans un e-mail, introduis « un problème », puis reparle du « problème ».', quiz: { question: '___ application est prête.', options: ['La', 'L’', 'Une'], answer: 1, explanation: '« Application » commence par une voyelle : on écrit « l’application ». ' } },
  { description: 'Accorder les noms et les déterminants.', rule: 'Le genre (masculin/féminin) et le nombre (singulier/pluriel) se retrouvent souvent dans l’article et l’adjectif.', examples: ['Un nouveau message.', 'Une nouvelle version.', 'Des messages importants.'], caution: 'Le genre d’un mot ne dépend pas toujours de la personne ou de l’objet réel.', tip: 'Apprends chaque nouveau nom avec son article : « la réunion », « le délai ».', quiz: { question: 'Choisis la forme correcte : ___ réunions.', options: ['Les', 'La', 'Le'], answer: 0, explanation: '« Réunions » est pluriel : on utilise « les ». ' } },
  { description: 'Faire correspondre l’adjectif au nom.', rule: 'Un adjectif s’accorde généralement avec le nom : un projet clair, une consigne claire, des projets clairs.', examples: ['Le besoin est précis.', 'La demande est précise.', 'Les consignes sont précises.'], caution: 'Certains adjectifs changent beaucoup : beau/belle, nouveau/nouvelle.', tip: 'Relis les groupes nom + adjectif avant d’envoyer un message.', quiz: { question: 'Une solution ___.', options: ['simple', 'simples', 'simplent'], answer: 0, explanation: 'Au féminin singulier, « simple » ne change pas ici.' } },
  { description: 'Dire non, ne plus faire ou ne jamais faire.', rule: 'La négation encadre le verbe : ne… pas, ne… jamais, ne… plus. Devant une voyelle, ne devient n’.', examples: ['Je ne comprends pas.', 'Nous ne travaillons jamais le dimanche.', 'Elle n’utilise plus cette version.'], caution: 'À l’oral, « ne » disparaît souvent, mais garde-le dans un écrit soigné.', tip: 'Prépare une phrase négative utile : « Je ne suis pas disponible vendredi. »', quiz: { question: 'Nous ___ utilisons plus ce fichier.', options: ['ne', 'pas', 'jamais'], answer: 0, explanation: 'La négation complète est « nous ne… utilisons plus ». ' } },
  { description: 'Poser des questions simples et précises.', rule: 'Tu peux utiliser l’intonation, « est-ce que », l’inversion ou un mot interrogatif : où, quand, pourquoi, comment.', examples: ['Est-ce que la réunion commence à neuf heures ?', 'Où se trouve le document ?', 'Pourquoi le test échoue-t-il ?'], caution: 'Après un mot interrogatif, n’ajoute pas toujours « est-ce que » : « Où vas-tu ? » est correct.', tip: 'En réunion, commence par « Est-ce que vous pouvez préciser… ? »', quiz: { question: '___ est-ce que tu envoies le rapport ?', options: ['Quand', 'Qui', 'Combien'], answer: 0, explanation: '« Quand » demande un moment ou une date.' } },
  { description: 'Exprimer l’appartenance.', rule: 'Mon/ton/son, notre/votre/leur s’accordent avec l’objet possédé, pas avec la personne qui possède.', examples: ['Mon équipe prépare la démo.', 'Sa collègue arrive.', 'Leurs documents sont prêts.'], caution: 'Devant un nom féminin qui commence par une voyelle, on dit « mon amie » pour faciliter la prononciation.', tip: 'Présente ton travail : « Mon projet », « notre client », « vos retours ».', quiz: { question: 'Nous présentons ___ projet.', options: ['notre', 'nos', 'votre'], answer: 0, explanation: '« Projet » est singulier : « notre projet ». ' } },
  { description: 'Montrer ou désigner une personne, une chose ou une idée.', rule: 'Ce, cet, cette, ces accompagnent le nom. « Cet » s’emploie devant un masculin commençant par voyelle ou h muet.', examples: ['Ce fichier est utile.', 'Cet e-mail est clair.', 'Cette version est stable.', 'Ces tests sont rapides.'], caution: '« Cet » ne marque pas le féminin : on dit « cette application ».', tip: 'Utilise-les pour désigner un élément précis durant une démo.', quiz: { question: '___ interface est plus simple.', options: ['Cette', 'Cet', 'Ce'], answer: 0, explanation: '« Interface » est féminin singulier : « cette ». ' } },
  { description: 'Situer une action dans l’espace et le temps.', rule: 'À indique souvent un lieu ou une heure ; dans indique un délai ; depuis indique le point de départ d’une durée.', examples: ['La réunion est à Paris.', 'Le point commence à 14 h.', 'Je réponds dans une heure.', 'Nous travaillons ici depuis lundi.'], caution: '« Dans deux jours » est futur ; « depuis deux jours » continue jusqu’à maintenant.', tip: 'Ajoute un lieu ou une heure à tes phrases pour les rendre actionnables.', quiz: { question: 'Le déploiement aura lieu ___ deux jours.', options: ['dans', 'depuis', 'à'], answer: 0, explanation: '« Dans deux jours » annonce un moment futur.' } },
  { description: 'Donner une consigne ou un conseil.', rule: 'L’impératif s’emploie sans pronom sujet : regarde, regardons, regardez. Place les pronoms après le verbe à l’affirmatif.', examples: ['Envoie le lien au client.', 'Vérifions les données.', 'Prenez des notes.'], caution: 'Avec les verbes en -er et « tu », on enlève souvent le -s : « regarde ».', tip: 'Dans une documentation, utilise des consignes courtes : « Cliquez », « Ajoutez », « Vérifiez ».', quiz: { question: '___ le fichier avant la réunion.', options: ['Envoie', 'Tu envoies', 'Envoyez-vous'], answer: 0, explanation: 'L’impératif avec « tu » est « envoie ». ' } },
];

const a2Details = [
  ['Passé composé avec avoir', 'Raconter une action terminée.', 'Le passé composé se forme avec avoir au présent + participe passé.', ['J’ai envoyé le compte rendu.', 'Nous avons corrigé le bug.', 'Ils ont choisi une solution.'], 'Ne confonds pas « j’ai parlé » avec « je parlais » : le premier fait avancer le récit.', 'Dans un bilan, liste les actions terminées au passé composé.', 'Hier, nous ___ la démo.', ['avons préparé', 'préparions', 'préparerons'], 0, 'Une action terminée hier : « nous avons préparé ».'],
  ['Passé composé avec être', 'Parler des mouvements et des changements d’état.', 'Certains verbes se conjuguent avec être : aller, venir, arriver, partir, entrer, sortir, naître, mourir et les verbes pronominaux.', ['Elle est arrivée tôt.', 'Nous sommes partis après la réunion.', 'Ils se sont connectés.'], 'Avec être, le participe passé s’accorde généralement avec le sujet.', 'Note les verbes les plus fréquents avec une phrase modèle.', 'Elles ___ arrivées à l’heure.', ['sont', 'ont', 'avaient'], 0, 'Avec « arriver », on emploie être : elles sont arrivées.'],
  ['Participes passés irréguliers', 'Reconnaître les formes fréquentes du passé composé.', 'Certains participes ne suivent pas la règle en -é : faire → fait, prendre → pris, voir → vu, écrire → écrit.', ['J’ai fait une sauvegarde.', 'Nous avons pris une décision.', 'Elle a écrit au client.'], 'Ne crée pas un participe régulier : on ne dit pas « prendé ».', 'Garde une liste courte des verbes utilisés dans ton travail.', 'Nous avons ___ le message.', ['écrit', 'écrivé', 'écrire'], 0, 'Le participe passé de « écrire » est « écrit ».'],
  ['Imparfait', 'Décrire un contexte, une habitude ou une action en cours.', 'L’imparfait se forme à partir de nous au présent : nous travaillons → je travaillais.', ['Le serveur était lent.', 'Nous travaillions chaque matin.', 'Il pleuvait pendant la démo.'], 'L’imparfait pose souvent le décor, il ne raconte pas l’événement principal.', 'Dans un récit, commence par le contexte avant de donner l’action importante.', 'Avant, nous ___ à distance.', ['travaillions', 'avons travaillé', 'travaillerons'], 0, 'Une habitude passée se raconte à l’imparfait.'],
  ['Différence entre passé composé et imparfait', 'Choisir le temps du décor et celui de l’événement.', 'L’imparfait décrit le contexte ou une habitude ; le passé composé raconte l’action terminée qui arrive.', ['Je travaillais quand le client a appelé.', 'Il pleuvait ; nous avons annulé la sortie.', 'Pendant que je lisais, le message est arrivé.'], 'Les deux temps se complètent souvent dans une même phrase.', 'Cherche ce qui était en cours et ce qui s’est produit.', 'Je ___ quand tu as appelé.', ['travaillais', 'ai travaillé', 'travaillerai'], 0, 'L’action en cours est à l’imparfait : « je travaillais ».'],
  ['Futur proche', 'Parler d’une intention ou d’une action imminente.', 'Le futur proche se construit avec aller au présent + infinitif.', ['Je vais envoyer le lien.', 'Nous allons commencer la réunion.', 'Ils vont publier la version.'], 'Après « aller », le deuxième verbe reste à l’infinitif.', 'Utilise-le pour annoncer la prochaine étape à l’oral.', 'Nous allons ___ le test.', ['lancer', 'lançons', 'lancé'], 0, 'Après « allons », le verbe reste à l’infinitif.'],
  ['Futur simple', 'Parler de projets, prévisions et promesses.', 'Le futur simple utilise l’infinitif + -ai, -as, -a, -ons, -ez, -ont.', ['Je terminerai demain.', 'Nous répondrons au client.', 'Le projet sera prêt lundi.'], 'Les verbes être et avoir changent de radical : je serai, j’aurai.', 'Dans un e-mail, utilise-le pour annoncer une échéance claire.', 'Je vous ___ le document demain.', ['enverrai', 'envoie', 'envoyais'], 0, 'Une action future : « j’enverrai ».'],
  ['Pronoms compléments directs', 'Éviter de répéter un nom complément direct.', 'Le, la, les remplacent une personne ou une chose sans préposition : Je vois le fichier → Je le vois.', ['Je le partage.', 'Nous la testons.', 'Je les envoie.'], 'Le pronom se place avant le verbe conjugué.', 'Dans une conversation, remplace une répétition par le ou la.', 'La maquette ? Je ___ valide.', ['la', 'lui', 'y'], 0, '« La maquette » est un complément direct féminin : « je la valide ».'],
  ['Pronoms compléments indirects', 'Remplacer un complément introduit par à.', 'Lui et leur remplacent une personne après à : Je parle à Léa → Je lui parle.', ['Je lui réponds.', 'Nous leur écrivons.', 'Le chef leur téléphone.'], 'Ne dis pas « je le parle » : parler à quelqu’un demande « lui ».', 'Dans un e-mail, pense à « je lui répondrai demain ».', 'Je téléphone à mes collègues : je ___ téléphone.', ['leur', 'les', 'en'], 0, 'À mes collègues devient « leur ».'],
  ['Pronoms y et en', 'Remplacer un lieu, une chose avec à ou de, et une quantité.', 'Y remplace souvent à + chose ou un lieu ; en remplace de + chose ou une quantité.', ['J’y pense.', 'Nous en avons besoin.', 'Tu en veux deux ?'], 'Y ne remplace pas normalement une personne.', 'Mémorise des blocs : penser à → y penser ; avoir besoin de → en avoir besoin.', 'Ce projet ? J’___ pense.', ['y', 'en', 'le'], 0, 'Penser à quelque chose devient « y penser ».'],
  ['Comparatif et superlatif', 'Comparer des éléments et exprimer un maximum.', 'Plus/moins/aussi + adjectif + que compare ; le plus/la plus exprime le superlatif.', ['Cette option est plus simple que l’autre.', 'Le test est moins long.', 'C’est la version la plus stable.'], 'Avec un nom, utilise plus de/moins de : plus de temps.', 'Compare deux solutions dans une réunion pour justifier un choix.', 'Cette solution est ___ rapide que l’autre.', ['plus', 'le plus', 'très'], 0, 'Une comparaison à deux utilise « plus … que ».'],
  ['Adverbes fréquents', 'Préciser quand, comment ou à quel degré une action se fait.', 'Les adverbes comme souvent, déjà, encore, toujours et vraiment modifient le verbe ou l’adjectif.', ['Je réponds souvent le matin.', 'Le test est déjà terminé.', 'Cette explication est vraiment claire.'], 'La position peut changer le sens : « il a déjà envoyé ».', 'Ajoute un adverbe pour donner une information plus précise.', 'Nous avons ___ terminé.', ['déjà', 'très', 'beaucoup de'], 0, '« Déjà » précise qu’une action est terminée avant le moment attendu.'],
  ['Connecteurs simples', 'Relier des idées de manière logique.', 'Parce que donne une cause ; donc une conséquence ; mais une opposition ; puis une suite.', ['Le test échoue parce que la donnée manque.', 'La donnée manque, donc le test échoue.', 'Le délai est court, mais le plan est clair.'], 'N’utilise pas « parce que » après « donc » dans la même relation.', 'Choisis un connecteur plutôt que de faire des phrases trop courtes.', 'Le serveur est indisponible, ___ nous attendons.', ['donc', 'parce que', 'mais'], 0, 'La conséquence est introduite par « donc ».'],
  ['Relatifs simples : qui, que, où', 'Relier deux phrases sans répétition.', 'Qui remplace le sujet, que le complément direct et où un lieu ou un moment.', ['Le collègue qui présente arrive.', 'Le fichier que tu cherches est là.', 'Le jour où nous avons livré était important.'], 'Après « que », le sujet apparaît normalement juste après : « que tu cherches ».', 'Utilise-les pour rendre un e-mail plus fluide.', 'Le document ___ tu as envoyé est complet.', ['que', 'qui', 'où'], 0, '« Tu as envoyé le document » : le document est complément direct, donc « que ».'],
].map(([title, description, rule, examples, caution, tip, question, options, answer, explanation], index) => ({ description, rule, examples, caution, tip, quiz: { question, options, answer, explanation } }));

const levelDefinitions = [
  { id: 'a1', level: 'A1', title: 'Construire des phrases simples', objective: 'Poser des bases solides pour comprendre, répondre et décrire son quotidien.', color: 'sage', titles: ['Pronoms sujets', 'Être, avoir, aller et faire au présent', 'Verbes réguliers en -er, -ir et -re', 'Articles définis et indéfinis', 'Masculin, féminin, singulier et pluriel', 'Accord des adjectifs', 'Négation : ne… pas, ne… jamais, ne… plus', 'Questions : est-ce que, inversion, mots interrogatifs', 'Adjectifs possessifs', 'Adjectifs démonstratifs', 'Prépositions de lieu et de temps', 'Impératif'], details: a1Details },
  { id: 'a2', level: 'A2', title: 'Parler du passé et du futur', objective: 'Raconter, prévoir et mieux relier les idées dans des situations courantes.', color: 'apricot', titles: ['Passé composé avec avoir', 'Passé composé avec être', 'Participes passés irréguliers', 'Imparfait', 'Différence entre passé composé et imparfait', 'Futur proche', 'Futur simple', 'Pronoms compléments directs', 'Pronoms compléments indirects', 'Pronoms y et en', 'Comparatif et superlatif', 'Adverbes fréquents', 'Connecteurs simples', 'Relatifs simples : qui, que, où'], details: a2Details },
  { id: 'b1', level: 'B1', title: 'Expliquer et argumenter', objective: 'Exprimer des hypothèses, justifier un choix et construire un raisonnement clair.', color: 'sky', titles: ['Conditionnel présent', 'Conditionnel passé', 'Plus-que-parfait', 'Futur antérieur', 'Discours indirect au présent', 'Discours indirect au passé', 'Subjonctif présent', 'Indicatif ou subjonctif', 'Pronoms relatifs : dont, lequel, auquel', 'Voix passive', 'Mise en relief : c’est… qui / c’est… que', 'Cause, conséquence et but', 'Opposition et concession', 'Hypothèse avec si', 'Gérondif', 'Nominalisation'], details: [
    { description: 'Formuler une proposition, un souhait ou un conseil avec diplomatie.', rule: 'Le conditionnel présent se forme sur le radical du futur avec les terminaisons de l’imparfait : je voudrais, nous pourrions.', examples: ['Je voudrais proposer une autre option.', 'Nous pourrions tester cette approche.', 'Le client apprécierait un délai plus court.'], caution: 'Après si, n’emploie pas le conditionnel : « si nous avions », pas « si nous aurions ».', tip: 'En réunion, « je proposerais » rend une suggestion plus souple.', quiz: { question: 'Nous ___ organiser un test.', options: ['pourrions', 'pouvons', 'pourrons'], answer: 0, explanation: '« Pourrions » exprime une proposition au conditionnel.' } },
    { description: 'Parler d’une action qui aurait pu se produire.', rule: 'Le conditionnel passé se forme avec avoir ou être au conditionnel + participe passé.', examples: ['Nous aurions pu prévenir le client.', 'Elle serait venue plus tôt.', 'J’aurais choisi une autre solution.'], caution: 'Il sert souvent à exprimer un regret, une information non confirmée ou une conséquence passée.', tip: 'Utilise-le avec mesure dans un compte rendu : « Nous aurions pu… ».', quiz: { question: 'J’___ répondre plus tôt.', options: ['aurais pu', 'ai pu', 'pourrais'], answer: 0, explanation: 'Le conditionnel passé est « aurais pu ». ' } },
  ] },
  { id: 'b2', level: 'B2', title: 'Nuancer et écrire avec précision', objective: 'Développer un français précis, structuré et adapté au contexte professionnel.', color: 'lavender', titles: ['Subjonctif passé', 'Hypothèse irréelle au présent et au passé', 'Concordance des temps', 'Participe présent et adjectif verbal', 'Accord complexe du participe passé', 'Pronoms doubles', 'Prépositions complexes', 'Connecteurs avancés', 'Reformulation', 'Opinion nuancée', 'Registre professionnel', 'Ponctuation et texte argumentatif'], details: [
    { description: 'Exprimer une réaction, un doute ou un jugement sur une action déjà accomplie.', rule: 'Le subjonctif passé se forme avec avoir ou être au subjonctif + participe passé : que j’aie compris, qu’elle soit arrivée.', examples: ['Je suis heureux que vous ayez réussi.', 'Il doute qu’elle soit arrivée.', 'Bien que nous ayons testé, le risque reste présent.'], caution: 'Le subjonctif passé situe l’action avant le moment de la réaction.', tip: 'Dans un bilan, il aide à commenter une action déjà faite avec nuance.', quiz: { question: 'Je doute qu’il ___ le message.', options: ['ait lu', 'a lu', 'lira'], answer: 0, explanation: 'Après « je doute que », on utilise le subjonctif passé : « ait lu ». ' } },
    { description: 'Exprimer une situation imaginaire et ses conséquences.', rule: 'Si + imparfait → conditionnel présent ; si + plus-que-parfait → conditionnel passé.', examples: ['Si nous avions plus de temps, nous testerions mieux.', 'Si elle avait reçu le lien, elle serait venue.', 'Je choisirais cette option si le budget le permettait.'], caution: 'Après « si », le conditionnel ne s’emploie pas.', tip: 'Pour discuter d’un risque, formule clairement la condition puis la conséquence.', quiz: { question: 'Si nous avions le budget, nous ___ cette solution.', options: ['choisirions', 'choisirons', 'choisissons'], answer: 0, explanation: 'Si + imparfait appelle le conditionnel présent : « choisirions ». ' } },
  ] },
  { id: 'c1', level: 'C1', title: 'Communiquer avec maîtrise', objective: 'Argumenter avec finesse, structurer des contenus complexes et adapter son registre.', color: 'rose', titles: ['Subjonctif dans les structures complexes', 'Infinitif passé', 'Tournures impersonnelles', 'Inversion soutenue', 'Concession avancée', 'Modalisation et nuance', 'Synthèse de documents', 'Argumentation complexe', 'Cohésion textuelle', 'Registres de langue', 'Précision lexicale et collocations', 'Correction des erreurs récurrentes'], details: [
    { description: 'Employer le subjonctif dans des enchaînements plus élaborés.', rule: 'Dans les structures de concession, de but ou de restriction, le subjonctif traduit une position nuancée : quoique, pourvu que, à moins que.', examples: ['Quoique la solution soit coûteuse, elle reste pertinente.', 'À moins que le client ne refuse, nous avancerons.', 'Pourvu que les tests soient concluants, la livraison aura lieu.'], caution: 'Le « ne » dans « à moins que » est souvent explétif : il ne marque pas une négation.', tip: 'Utilise une seule structure complexe par phrase pour garder une argumentation lisible.', quiz: { question: '___ le délai soit court, le plan reste réaliste.', options: ['Quoique', 'Parce que', 'Donc'], answer: 0, explanation: '« Quoique » introduit une concession et appelle le subjonctif.' } },
    { description: 'Situer une action accomplie avant une autre action.', rule: 'L’infinitif passé se forme avec avoir ou être à l’infinitif + participe passé : après avoir vérifié, après être arrivé.', examples: ['Après avoir relu l’e-mail, je l’ai envoyé.', 'Après être arrivée, elle a ouvert la réunion.', 'Merci d’avoir signalé le problème.'], caution: 'Avec être, le participe s’accorde avec le sujet : « après être arrivée ».', tip: 'Dans un compte rendu, il permet de condenser deux actions.', quiz: { question: 'Après ___ le test, nous avons déployé.', options: ['avoir validé', 'avons validé', 'valider'], answer: 0, explanation: 'Après + infinitif passé : « après avoir validé ». ' } },
  ] },
];

export const grammarLevels = levelDefinitions.map((definition) => ({
  ...definition,
  lessons: definition.titles.map((title, index) => makeLesson(definition.level, index + 1, title, definition.details[index])),
}));

export const grammarLessons = grammarLevels.flatMap((level) => level.lessons);

export function findGrammarLesson(id) {
  return grammarLessons.find((lesson) => lesson.id === id);
}
